<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Fundacion Proinso</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #2485E6;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            @media(max-width:600px) {
                h1 {
                    font-size: 40px;
                    font-weight: 200;
                }
            }
        </style>
    </head>
    <body>
        <h1>Fundación Proinso</h1>
        <?php if (isset($operacion)) : ?>
            <p><?= ($operacion); ?>!</p>
        <?php else: ?>
            <p><a href="http://fundacionproinso.org">Fundación Proinso</a></p>
        <?php endif; ?>
         <input type="hidden" id="btnSalir">
        <script>
            setTimeout(() => {
                btnSalir.click()
            }, 3000);
        </script>
    </body>
</html>
